name: build ⚙️

on: [ push, pull_request ]

jobs:
  main:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v6
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install packages
      run: sudo apt-get -y install pandoc
    - name: Install requirements 📦
      run: |
        pip3 install -e .
        pip3 install ".[dev]"
        pip3 install ".[docs]"
        pip3 install ".[test]"
    - name: run tests ⚙️
      run: pytest tests/
    - name: run tests in offline mode
      if: matrix.python-version == '3.12'
      run: |
          pytest tests/\
            -m "not online" \
            --disable-socket \
            --deselect="tests/doctests/wcs_thredds.txt::wcs_thredds.txt" \
            --deselect="tests/doctests/wfs_MapServerWFSCapabilities.txt::wfs_MapServerWFSCapabilities.txt" \
            --deselect="tests/doctests/wms_geoserver_mass_gis.txt::wms_geoserver_mass_gis.txt"
    - name: run coveralls ⚙️
      run: coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_PARALLEL: true
        COVERALLS_FLAG_NAME: "${{ matrix.python-version }}"
        COVERALLS_SERVICE_NAME: github
        COVERALLS_SERVICE_JOB_ID: "${{ github.run_id }}"
        COVERALLS_SERVICE_NUMBER: "${{ github.workflow }}-${{ github.run_number }}"
    - name: build docs 🏗️
      run: cd docs && make html
    - name: run flake8 ⚙️
      run: flake8 owslib/
